//! Golden corpus parity test: replay the canonical `decimal_string()` outputs
//! recorded from the Python backend (`src/hypeedge/api/schemas.py`) through our
//! fixed-point `Decimal`.
//!
//! The corpus lives in `tests/fixtures/golden_decimal.jsonl`, generated by
//! `docs/scripts/record_golden.py` (or by hand against a running Python venv).
//! Each row is `{"input": "...", "canonical": "..."|null, "strict": bool}`.
//!
//! `strict` rows go through `from_str_strict` and must reproduce `canonical`
//! exactly; non-strict rows are float-`str()` coercion outputs and go through
//! `from_str_lenient` (mirroring how Python's `DecimalValue` accepts floats).

use hypeedge_domain::decimal::Decimal;

#[test]
fn golden_decimal_corpus_parity() {
    let corpus_path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/golden_decimal.jsonl"
    );
    let content = std::fs::read_to_string(corpus_path).expect("corpus file should exist");
    let mut checked = 0usize;
    for (idx, line) in content.lines().enumerate() {
        if line.trim().is_empty() {
            continue;
        }
        let row: serde_json::Value = serde_json::from_str(line).unwrap();
        let input = row["input"].as_str().unwrap();
        let strict = row["strict"].as_bool().unwrap_or(false);
        let canonical = row["canonical"].as_str();

        let result = if strict {
            Decimal::from_str_strict(input)
        } else {
            Decimal::from_str_lenient(input)
        };

        match (canonical, result) {
            (Some(expected), Ok(parsed)) => {
                let actual = parsed.to_string();
                assert_eq!(
                    actual, expected,
                    "row {idx}: input={input:?} strict={strict} expected canonical {expected:?}, got {actual:?}"
                );
            }
            (None, Err(_)) => {
                // Python rejected it; we rejected too — parity satisfied
                // regardless of the specific reason.
            }
            (Some(_), Err(e)) => panic!("row {idx}: input={input:?} failed to parse: {e}"),
            (None, Ok(parsed)) => {
                panic!("row {idx}: input={input:?} parsed to {parsed} but Python rejected it")
            }
        }
        checked += 1;
    }
    assert!(checked > 0, "corpus must not be empty");
    eprintln!("golden decimal corpus: {checked} rows verified");
}
