[package]
name = "hypeedge_domain"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
ethnum = { workspace = true }
async-trait = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
